package com.xiaominfo.knife4j.webflux;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class Knife4jWebfluxDemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(Knife4jWebfluxDemoApplication.class, args);
    }

}
